from django.conf.urls import patterns, url
from pname import views

urlpatterns = patterns('',
	          url(r'^$', views.home, name = 'home'),
		  url(r'home.html/$', views.home, name = 'home'),
		  url(r'search.html/$', views.search, name = 'search'),
		  url(r'names_list.html/$', views.namelist, name = 'namelist'),
		  url(r'temp.html/$', views.tempor, name = 'tempor'),
		  #url(r'admin_search.html/$', views.search, name = 'admin_search'),
		  url(r'addword.html/$', views.addword2, name = 'addword'),
		  url(r'addword2.html/$', views.addword2, name = 'addword2'),
		  #url(r'admin_addword.html/$', views.addword2, name = 'addword'),
		  url(r'addword3.html/$', views.addword3, name = 'addword3'),
		  #url(r'admin_addword3.html/$', views.addword3, name = 'addword3'),
		  url(r'addword4.html/$', views.addword4, name = 'addword4'),
		  url(r'addword5.html/$', views.addword5, name = 'addword4'),
		  url(r'help.html/$', views.helper, name = 'addword4'),
		  #url(r'admin_addword4.html/$', views.addword4, name = 'addword'),
		  url(r'record.html/$', views.recording, name = 'recording'),
		  #url(r'recording2.html/$', views.recording2, name = 'recording2'),
		  #url(r'addreq.html/$', views.addreq, name = 'addreq'),
		  #url(r'displayallwords.html/$', views.displayallwords, name = 'displayallwords'),
		  #url(r'admin_displayallwords.html/$', views.displayallwords, name = 'admin_displayallwords'),
		  url(r'fest.html/$', views.fest, name = 'fest'),
		  #url(r'admin_fest.html/$', views.fest, name = 'adminfest'),
		  url(r'fest2.html/$', views.fest2, name = 'fest2'),
		  #url(r'admin_fest2.html/$', views.fest2, name = 'adminfest2'),
		  #url(r'admin1.html/$', views.admin1, name = 'admin1'),
		  #url(r'admin2.html/$', views.admin2, name = 'admin2'),
		  #url(r'adminlogout.html/$', views.adminlogout, name = 'adminlogout'),
		 )
